GET http://localhost:3003/test
Content-Type: application/json
###

POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Silveira",
    "module": 2
}

###

GET http://localhost:3003/class
###

POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Chris",
    "email": "chris@chris.com",
    "birth": "01/01/1111",
    "class_id": 1,
    "hobbies": "programar"
}
