GET http://localhost:3003/test
Content-Type: application/json
###

POST http://localhost:3003/class
Content-Type: application/json

{
    "name": "Einstein",
    "module": "5"
}

###

GET http://localhost:3003/class

###
PUT http://localhost:3003/class/1656081120304
Content-Type: application/json

{
    "module": "2"
}